name: Run TestNG Test Suite

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch
    workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  test:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java (JDK 11 in this example)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'  # You can also use 'zulu' or 'temurin'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install dependencies and build the project
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # Run the TestNG test suite
      - name: Run TestNG Test Suite
        run: mvn test -DsuiteXmlFile=test-suite.xml  # Assuming test-suite.xml is in the root directory
        env:
          MAVEN_OPTS: "-Xmx2g"  # Optional, to set JVM options if needed

      # Upload TestNG results as an artifact (optional)
      - name: Upload TestNG results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-results
          path: target/surefire-reports/  # Adjust if your reports are stored elsewhere
